package com.ivarna.fluxlinux.core.terminal

import android.content.Context
import android.util.Log
import com.ivarna.fluxlinux.BuildConfig
import java.io.File

/**
 * Single source of truth for host (embedded Termux-class) package paths.
 *
 * Kotlin, generated `fluxlinux-host.env`, and bootstrap path rewrites all derive
 * from [PACKAGE]. Never hardcode `com.termux` defaults at call sites.
 * Mirrors termux-lib `TermuxHostPaths` with the package pinned to the flavor
 * applicationId via `BuildConfig.APPLICATION_ID`.
 */
object TermuxHostPaths {
    val PACKAGE: String get() = BuildConfig.APPLICATION_ID
    const val STOCK_PACKAGE = "com.termux"

    /** `/data/data/<package>` */
    val DATA_ROOT: String get() = "/data/data/$PACKAGE"
    val STOCK_DATA_ROOT: String get() = "/data/data/$STOCK_PACKAGE"

    val FILES: String get() = "$DATA_ROOT/files"
    val PREFIX: String get() = "$FILES/usr"
    val HOME: String get() = "$FILES/home"
    val TMPDIR: String get() = "$PREFIX/tmp"
    /**
     * Host-only proot glue/f2fs probe dir. Must **not** be the `--shared-tmp`
     * bind (`$PREFIX/tmp`): guest/root `chmod`/`chown` there makes glue fail
     * with `can't create temporary directory: Permission denied`.
     */
    val PROOT_TMP: String get() = "$FILES/proot-tmp"
    val BIN: String get() = "$PREFIX/bin"
    val LIB: String get() = "$PREFIX/lib"
    val SSL_CERT: String get() = "$PREFIX/etc/tls/cert.pem"
    val PROOT_DISTRO: String get() = "$BIN/proot-distro"
    const val TERMUX_VERSION = "flux-host"

    /** Relative path under app filesDir for generated shell env. */
    const val HOST_ENV_REL = "usr/etc/fluxlinux-host.env"

    private const val TAG = "TermuxHostPaths"
    private const val MAX_REWRITE_BYTES = 2_000_000L

    fun setupTermuxMarker(ctx: Context): File =
        File(ctx.filesDir, "home/.fluxlinux/setup_termux.done")

    fun clearSetupTermuxMarker(ctx: Context): Boolean =
        setupTermuxMarker(ctx).delete()

    fun libProot(ctx: Context): File =
        File(ctx.applicationInfo.nativeLibraryDir, "libproot.so")

    fun libLoader(ctx: Context): File =
        File(ctx.applicationInfo.nativeLibraryDir, "libloader.so")

    fun libLoader32(ctx: Context): File =
        File(ctx.applicationInfo.nativeLibraryDir, "libloader32.so")

    fun libBash(ctx: Context): File =
        File(ctx.applicationInfo.nativeLibraryDir, "libbash.so")

    /** W^X-safe Pulse daemon (same rule as [libBash]). */
    fun libPulseaudio(ctx: Context): File =
        File(ctx.applicationInfo.nativeLibraryDir, "libpulseaudio.so")

    fun libPactl(ctx: Context): File =
        File(ctx.applicationInfo.nativeLibraryDir, "libpactl.so")

    fun termuxExec(ctx: Context): File =
        File(ctx.filesDir, "usr/lib/libtermux-exec.so")

    fun homeDir(ctx: Context): File =
        File(ctx.filesDir, "home")

    fun hostScript(ctx: Context, name: String): File =
        File(homeDir(ctx), name)

    fun hostEnvFile(filesDir: File): File =
        File(filesDir, HOST_ENV_REL)

    /** Relative path under filesDir for proot-distro login __init__.py (W^X patch target). */
    const val PROOT_DISTRO_LOGIN_INIT_REL =
        "usr/lib/python3.14/site-packages/proot_distro/commands/login/__init__.py"

    /** Replace stock Termux data-root paths with this package's paths. */
    fun rewriteStockPaths(text: String): String =
        text.replace(STOCK_DATA_ROOT, DATA_ROOT)

    /**
     * Write `usr/etc/fluxlinux-host.env` for shell scripts to source.
     * Generated from this object only — do not hand-edit on device.
     *
     * When [ctx] is provided, also pins W^X-safe `PD_PROOT_BIN` / `PROOT_LOADER{,_32}`
     * to jniLibs under `nativeLibraryDir` (required on targetSdk 36).
     */
    fun writeHostEnvFile(filesDir: File, ctx: Context? = null): File {
        val f = hostEnvFile(filesDir)
        f.parentFile?.mkdirs()
        val wxBlock = if (ctx != null) {
            """
            |export PD_PROOT_BIN="${libProot(ctx).absolutePath}"
            |export PROOT_LOADER="${libLoader(ctx).absolutePath}"
            |export PROOT_LOADER_32="${libLoader32(ctx).absolutePath}"
            |export PD_PULSEAUDIO_BIN="${libPulseaudio(ctx).absolutePath}"
            |export PD_PACTL_BIN="${libPactl(ctx).absolutePath}"
            |""".trimMargin()
        } else {
            ""
        }
        f.writeText(
            """
            |# Generated by TermuxHostPaths.kt — single source of truth. Do not edit.
            |export TERMUX_APP__PACKAGE_NAME="$PACKAGE"
            |export TERMUX_X11_OVERRIDE_PACKAGE="$PACKAGE"
            |export TERMUX__PREFIX="$PREFIX"
            |export TERMUX__HOME="$HOME"
            |export PREFIX="$PREFIX"
            |export HOME="$HOME"
            |export TMPDIR="$TMPDIR"
            |export PROOT_TMP_DIR="$PROOT_TMP"
            |export TERMUX_VERSION="$TERMUX_VERSION"
            |export SSL_CERT_FILE="$SSL_CERT"
            |export CURL_CA_BUNDLE="$SSL_CERT"
            |export PATH="$BIN:$BIN/applets:/system/bin:/system/xbin${'$'}{PATH:+:${'$'}PATH}"
            |export LD_LIBRARY_PATH="$LIB${'$'}{LD_LIBRARY_PATH:+:${'$'}LD_LIBRARY_PATH}"
            |$wxBlock
            |""".trimMargin()
        )
        return f
    }

    /**
     * Patch proot-distro so `PROOT_LOADER` / `PROOT_LOADER_32` / `PROOT_TMP_DIR`
     * are passed through to the **host** proot process.
     *
     * Stock only allows `PROOT_NO_SECCOMP` / `PROOT_VERBOSE`.
     * Without the loader env, proot falls back to `$PREFIX/libexec/proot/loader`
     * which is not executable under targetSdk 36 W^X →
     * `proot error: execve("/usr/bin/bash"): Permission denied`.
     * Without `PROOT_TMP_DIR`, glue/f2fs temp dirs go to an unwritable default →
     * `can't create temporary directory` / `can't create glue rootfs`.
     *
     * Idempotent — safe to call on every host prepare.
     *
     * @return true when the file was patched (or already patched)
     */
    fun patchProotDistroLoaderPassThrough(filesDir: File): Boolean {
        val loginInit = File(filesDir, PROOT_DISTRO_LOGIN_INIT_REL)
        if (!loginInit.isFile) {
            Log.w(TAG, "proot-distro login __init__.py missing: ${loginInit.absolutePath}")
            return false
        }
        return try {
            var content = loginInit.readText(Charsets.UTF_8)
            val full =
                "\"PROOT_NO_SECCOMP\", \"PROOT_VERBOSE\", \"PROOT_LOADER\", \"PROOT_LOADER_32\", \"PROOT_TMP_DIR\""
            // Already fully patched
            if (content.contains("\"PROOT_LOADER\"") &&
                content.contains("\"PROOT_LOADER_32\"") &&
                content.contains("\"PROOT_TMP_DIR\"")
            ) {
                return true
            }
            val replacements = listOf(
                "\"PROOT_NO_SECCOMP\", \"PROOT_VERBOSE\", \"PROOT_LOADER\", \"PROOT_LOADER_32\"" to full,
                "\"PROOT_NO_SECCOMP\", \"PROOT_VERBOSE\", \"PROOT_LOADER\"" to full,
                "\"PROOT_NO_SECCOMP\", \"PROOT_VERBOSE\"" to full,
            )
            var replaced = false
            for ((from, to) in replacements) {
                if (content.contains(from)) {
                    content = content.replace(from, to)
                    replaced = true
                    break
                }
            }
            if (!replaced) {
                Log.w(TAG, "proot-distro allowlist pattern not found; cannot patch PROOT_*")
                return false
            }
            loginInit.writeText(content, Charsets.UTF_8)
            Log.i(TAG, "patched proot-distro to pass PROOT_LOADER / PROOT_LOADER_32 / PROOT_TMP_DIR")
            true
        } catch (e: Exception) {
            Log.e(TAG, "failed to patch proot-distro PROOT_* pass-through", e)
            false
        }
    }

    /**
     * After bootstrap extract (and before host setup): rewrite residual
     * `/data/data/com.termux/...` text under the prefix, patch proot-distro
     * W^X loader pass-through, then write host env file.
     *
     * @param ctx optional; when set, host env also pins PD_PROOT_BIN / PROOT_LOADER*
     * @return number of stock-path files rewritten
     */
    fun applyPackageToExtractedPrefix(filesDir: File, ctx: Context? = null): Int {
        var rewritten = 0
        val roots = listOf(
            File(filesDir, "usr/bin"),
            File(filesDir, "usr/etc"),
            File(filesDir, "usr/share"),
            File(filesDir, "usr/lib/python3.14/site-packages/proot_distro"),
            File(filesDir, "usr/include/termux-exec"),
        )
        for (root in roots) {
            if (!root.exists()) continue
            root.walkTopDown().forEach { file ->
                if (!file.isFile) return@forEach
                val len = file.length()
                if (len == 0L || len > MAX_REWRITE_BYTES) return@forEach
                try {
                    val bytes = file.readBytes()
                    // Skip binaries (NUL in first 512 bytes)
                    val scan = minOf(bytes.size, 512)
                    for (i in 0 until scan) {
                        if (bytes[i] == 0.toByte()) return@forEach
                    }
                    val text = bytes.toString(Charsets.UTF_8)
                    if (!text.contains(STOCK_DATA_ROOT)) return@forEach
                    file.writeText(rewriteStockPaths(text), Charsets.UTF_8)
                    rewritten++
                } catch (e: Exception) {
                    Log.w(TAG, "skip rewrite ${file.absolutePath}: ${e.message}")
                }
            }
        }
        // W^X: must run after any rewrite of proot_distro tree (and every prepareHost).
        patchProotDistroLoaderPassThrough(filesDir)
        writeHostEnvFile(filesDir, ctx)
        ensureHostTmpDirs(filesDir)
        if (rewritten > 0) {
            Log.i(TAG, "rewrote $rewritten file(s): $STOCK_DATA_ROOT → $DATA_ROOT")
        }
        return rewritten
    }

    /**
     * Create host tmp dirs used by proot + X11.
     * [PROOT_TMP] is private (0700). Shared [TMPDIR] is 0777 so guest uid 1000
     * can write `/tmp` under `--shared-tmp` even without uid mapping.
     * Full pass once per process; later calls only re-run if a dir went missing
     * (re-extract / guest `rm`).
     */
    fun ensureHostTmpDirs(filesDir: File = File(FILES)) {
        if (hostTmpDirsDone.get() &&
            File(filesDir, "usr/tmp/.X11-unix").isDirectory &&
            File(filesDir, "proot-tmp").isDirectory
        ) return
        val shared = File(filesDir, "usr/tmp").also { it.mkdirs() }
        File(shared, ".X11-unix").mkdirs()
        val glue = File(filesDir, "proot-tmp").also { it.mkdirs() }
        shared.setReadable(true, false)
        shared.setWritable(true, false)
        shared.setExecutable(true, false)
        glue.setReadable(true, true)
        glue.setWritable(true, true)
        glue.setExecutable(true, true)
        restoreAppDataSelinux(shared, filesDir)
        hostTmpDirsDone.set(true)
    }

    private val hostTmpDirsDone = java.util.concurrent.atomic.AtomicBoolean(false)

    /**
     * Host PREFIX/tmp must keep the app_data_file label. A leftover tmpfs:s0
     * (older chroot start used chcon -R) makes termux-x11 fail to create
     * .X11-unix / lock files under enforcing SELinux.
     */
    private fun restoreAppDataSelinux(target: File, filesDir: File) {
        try {
            val clazz = Class.forName("android.os.SELinux")
            val get = clazz.getMethod("getFileContext", String::class.java)
            val set = clazz.getMethod("setFileContext", String::class.java, String::class.java)
            val want = get.invoke(null, filesDir.absolutePath) as? String ?: return
            if (want.isBlank() || want.contains("unlabeled")) return
            val have = get.invoke(null, target.absolutePath) as? String
            if (have == want) return
            set.invoke(null, target.absolutePath, want)
        } catch (_: Throwable) {
            // JVM unit tests / missing API / SELinux deny
        }
    }
}
